# Reference: https://golangci-lint.run/docs/configuration/file/
version: "2"
run:
  timeout: 10m
output:
  sort-order:
    - file
formatters:
  # https://golangci-lint.run/docs/formatters/
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
linters:
  # https://golangci-lint.run/docs/linters/
  default: none
  enable:
    - asciicheck
    - depguard
    - dupl
    - dupword
    - errcheck
    - errorlint
    - gosec
    - ineffassign
    - gocritic
    - govet
    - misspell
    - mirror
    - modernize
    - nolintlint
    - perfsprint
    - revive
    - staticcheck
    - testifylint
    - unused
    - usestdlibvars
    - usetesting
    - unconvert
    - wastedassign
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: "Use corresponding 'os' or 'io' functions instead."
            - pkg: "github.com/pkg/errors"
              desc: "Use 'errors' or 'fmt' instead of github.com/pkg/errors"
            - pkg: "golang.org/x/exp/slices"
              desc: "Use 'slices' instead."
    revive:
      # https://github.com/mgechev/revive/blob/master/defaults.toml
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
      enable-all-rules: true
      severity: error
      rules:
        - name: line-length-limit
          severity: error
          arguments: [120]
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: unhandled-error
          arguments:
          - "fmt.Println"
          - "fmt.Printf"
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true
